all:
	g++ -Wall parallel_impedance.cpp -o parallel_impedance
	g++ -Wall inverse_impedance.cpp -o inverse_impedance
	g++ -Wall rect2pol.cpp -o rect2pol
	g++ -Wall pol2rect.cpp -o pol2rect
clean:
	rm -rf parallel_impedance
	rm -rf inverse_impedance
	rm -rf rect2pol
	rm -rf pol2rect
